#use with:
# kubectl -n simpleapp apply -f thisFile.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-auth
type: kubernetes.io/basic-auth
stringData:
  username: simpleapp
  mongodb-password: simpleapp
  host: mongodb
  port: "27017"
  database: simpleapp
  mongodb-root-password: root
